# Form implementation generated from reading ui file 'user_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_user_widget(object):
    def setupUi(self, user_widget):
        user_widget.setObjectName("user_widget")
        user_widget.resize(350, 109)
        self.horizontalLayout = QtWidgets.QHBoxLayout(user_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(186, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.textBrowser = QtWidgets.QTextBrowser(parent=user_widget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.textBrowser.setStyleSheet("border: 1px solid rgba(71,121,214, 25);\n"
"border-radius: 20px;\n"
"background-color: rgba(71,121,214, 25);\n"
"padding:10px;\n"
"\n"
"")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.user_label = QtWidgets.QLabel(parent=user_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_label.sizePolicy().hasHeightForWidth())
        self.user_label.setSizePolicy(sizePolicy)
        self.user_label.setMinimumSize(QtCore.QSize(40, 40))
        self.user_label.setMaximumSize(QtCore.QSize(40, 40))
        self.user_label.setStyleSheet("")
        self.user_label.setText("")
        self.user_label.setPixmap(QtGui.QPixmap(":/image/user.png"))
        self.user_label.setScaledContents(True)
        self.user_label.setObjectName("user_label")
        self.horizontalLayout.addWidget(self.user_label)

        self.retranslateUi(user_widget)
        QtCore.QMetaObject.connectSlotsByName(user_widget)

    def retranslateUi(self, user_widget):
        _translate = QtCore.QCoreApplication.translate
        user_widget.setWindowTitle(_translate("user_widget", "Form"))
        self.textBrowser.setHtml(_translate("user_widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"> </span></p></body></html>"))

import ui_image_rc

if __name__ == '__main__':
    app = QtWidgets.QApplication([])
    win = QtWidgets.QWidget()
    Ui_user_widget().setupUi(win)
    win.show()
    app.exec()